$(document).ready(function(){
    $("#dhsButton").click(function(){
    $(".dhsImg").fadeToggle();
    });
    });
$(document).ready(function(){
    $("#icsaButton").click(function(){
    $(".icsaImg").fadeToggle();
    });
    });